##MULE_HOME : /app/speedy-gws/mule-standalone-3.2.1/
##DIRECTORIOSIAC : /var/backups/siac-speedy-26-10-15
- hosts: speedy
  remote_user: gwspeedy

  tasks:

  - name: Bajando mule
    wait_for: path={{ MULE_HOME }}/bin/.mule.pid state=present timeout=2
    register: pid_file
    ignore_errors: True

  - shell: "{{ MULE_HOME }}/bin/shutdown.sh"
    async: 45
    poll: 5
    when:  pid_file|success

# - name: respaldo original
#   shell: "cp -rp {{MULE_HOME}}/apps/captiveCore* {{DIRECTORIOSIAC}}/gwtsva/original-files"

#  - name: Borrando archivos productivos
#   file: "path={{MULE_HOME}}/apps/captiveCore state=absent "

  - name: Copia de archivos modificados
    shell: "cp -r /var/backups/siac-26-10-15/gwtsva/modified-files/captiveCore {{MULE_HOME}}/apps/ "

  - name: Copia de archivos jar
    shell: "cp /var/backups/siac-26-10-15/gwtsva/modified-files/*.jar {{MULE_HOME}}/lib/user/"

  - name: Copia de archivos .properties
    shell: "cp {{DIRECTORIOSIAC}}/gwtsva/original-files/captiveCore/classes/*.properties {{MULE_HOME}}/apps/captiveCore/classes/" 

  - name: Copia de archivos log4j
    shell: "cp {{DIRECTORIOSIAC}}/gwtsva/original-files/captiveCore/classes/log4j.xml {{MULE_HOME}}/apps/captiveCore/classes/"

  - name: Modifiacion de ccore.properties
    template: "src=templates/ccore.properties dest={{MULE_HOME}}/apps/captiveCore/classes/"
 

  - name: tunning para speedygws maxThreadsActive
    replace: "dest={{ MULE_HOME }}/apps/captiveCore/mule-config.xml regexp='maxThreadsActive=[^ ]*' replace='maxThreadsActive=\"750\"' backup=yes"
  - name: tunning para speedygws maxBufferSize 
    replace: "dest={{ MULE_HOME }}/apps/captiveCore/mule-config.xml regexp='maxBufferSize=[^ ]*' replace='maxBufferSize=\"150\"' backup=yes"
  - name: comentar spring-quartz
    replace: dest='{{ MULE_HOME }}/apps/captiveCore/spring-quartz.xml' regexp='(<ref bean=.getNotificationsTrigger. />)' replace='<!-- \1 -->' backup=yes
  - name: comentar spring-config 1
    replace: dest={{ MULE_HOME }}/apps/captiveCore/spring-config.xml regexp='(<ref bean=.loadProductsTrigger. />)' replace='<!-- \1 -->' backup=yes
  - name: comentar spring-config 2
    replace: dest={{ MULE_HOME }}/apps/captiveCore/spring-config.xml regexp='(<ref bean=.loadProductsTriggerClaroMusica. />)' replace='<!-- \1 -->' backup=yes
  - name: comentar spring-config 3
    replace: dest={{ MULE_HOME }}/apps/captiveCore/spring-config.xml regexp='(<ref bean=.loadProductsTriggerClaroMusicaNofit. />)' replace='<!-- \1 -->' backup=yes

  - name: Iniciar Core
    shell: "{{ MULE_HOME }}/bin/startup.sh"
    async: 45
    poll: 5

  - wait_for: "path={{ MULE_HOME }}/logs/mule.log search_regex='* DEPLOYED           *' timeout=350 delay=300"
